import "./globals.css";
import Header from "@/components/header";
import Footer from "@/components/footer";


export const metadata = {
  title: "Sport Market",
  description: "Generated by create next app",
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main>
        {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
